# Copyright 2020 Shift Cryptosecurity AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "bitbox02-rust-c"
version = "0.1.0"
authors = ["Shift Crypto AG <support@shiftcrypto.ch>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
bitbox02-rust = { path = "../bitbox02-rust", optional = true }
bitbox02 = { path = "../bitbox02", optional = true }
bitbox02-noise = { path = "../bitbox02-noise", optional = true }
util = { path = "../util" }
ethereum = { path = "../apps/ethereum", optional = true }
hex = { version = "0.4", default-features = false }
arrayref = "0.3.6"
sha2 = { version = "0.9.2", default-features = false, optional = true }

[features]
# Only one of the "target-" should be activated, which in turn defines/activates the dependent features.
target-bootloader = ["bootloader", "platform-bitbox02"]
target-bootloader-development = ["bootloader", "platform-bitbox02"]
target-bootloader-development-locked = ["bootloader", "platform-bitbox02"]
target-bootloader-production = ["bootloader", "platform-bitbox02"]
target-bootloader-btc = ["bootloader", "platform-bitbox02"]
target-bootloader-btc-development = ["bootloader", "platform-bitbox02"]
target-bootloader-btc-production = ["bootloader", "platform-bitbox02"]
target-bootloader-bitboxbase = ["bootloader", "platform-bitboxbase"]
target-bootloader-bitboxbase-development = ["bootloader", "platform-bitboxbase"]
target-bootloader-bitboxbase-production = ["bootloader", "platform-bitboxbase"]
target-firmware = ["firmware", "platform-bitbox02", "app-ethereum"]
target-firmware-btc = ["firmware", "platform-bitbox02"]
target-firmware-bitboxbase = ["firmware", "platform-bitboxbase"]
target-factory-setup = ["firmware", "platform-bitbox02"]
target-factory-setup-bitboxbase = ["firmware", "platform-bitboxbase"]
# add Rust features which are called in the C unit tests (currently there is only one target for C tests).
target-c-unit-tests = ["app-ethereum", "firmware"]

platform-bitbox02 = []
platform-bitboxbase = []

bootloader = []
firmware = ["bitbox02-rust", "bitbox02", "bitbox02-noise", "sha2"]

# Only to be enabled in unit tests.
testing = ["bitbox02/testing"]

app-ethereum = [
  "ethereum", # this is a dependency
  "bitbox02-rust/app-ethereum", # enable this feature in the dep
]
