# SPDX-License-Identifier: Apache-2.0

[package]
name = "bitbox02-rust-c"
version = "0.1.0"
authors = ["Shift Crypto AG <support@bitbox.swiss>"]
edition = "2024"
license = "Apache-2.0"

[dependencies]
bitbox02-rust = { path = "../bitbox02-rust", optional = true }
bitbox-aes = { path = "../bitbox-aes", optional = true }
bitbox02 = { path = "../bitbox02", optional = true }
bitbox02-noise = { path = "../bitbox02-noise", optional = true }
cortex-m = { workspace = true }
util = { path = "../util" }
bitbox-framed-serial-link = { path = "../bitbox-framed-serial-link" }
der =  { version = "0.7.9", default-features = false, optional = true }
hex = { workspace = true }
sha2 = { workspace = true, optional = true }
digest = { workspace = true, optional = true }
bitcoin = { workspace = true, optional = true }
bip39 = { workspace = true }
zeroize = { workspace = true }

[features]
# Only one of the "target-" should be activated, which in turn defines/activates the dependent features.
target-bb02-bl-multi = ["bootloader", "platform-bitbox02"]
target-bb02-bl-multi-development = ["bootloader", "platform-bitbox02"]
target-bb02-bl-multi-development-locked = ["bootloader", "platform-bitbox02"]
target-bb02-bl-multi-production = ["bootloader", "platform-bitbox02"]
target-bb02-bl-btconly = ["bootloader", "platform-bitbox02"]
target-bb02-bl-btconly-development = ["bootloader", "platform-bitbox02"]
target-bb02-bl-btconly-production = ["bootloader", "platform-bitbox02"]
target-bb02p-bl-multi = ["bootloader", "platform-bitbox02plus"]
target-bb02p-bl-multi-development = ["bootloader", "platform-bitbox02plus"]
target-bb02p-bl-multi-development-locked = ["bootloader", "platform-bitbox02plus"]
target-bb02p-bl-multi-production = ["bootloader", "platform-bitbox02plus"]
target-bb02p-bl-btconly = ["bootloader", "platform-bitbox02plus"]
target-bb02p-bl-btconly-development = ["bootloader", "platform-bitbox02plus"]
target-bb02p-bl-btconly-production = ["bootloader", "platform-bitbox02plus"]
target-firmware = ["firmware", "platform-bitbox02", "app-bitcoin", "app-litecoin", "app-ethereum", "app-u2f", "app-cardano"]
target-firmware-btc = ["firmware", "platform-bitbox02", "app-bitcoin"]
target-factory-setup = [
  # enable these features
  "factory-setup",
  "firmware",
  "platform-bitbox02",
  "dep:bitcoin",
]
# add Rust features which are called in the C unit tests (currently there is only one target for C tests).
target-c-unit-tests = [
  "app-bitcoin",
  "app-litecoin",
  "app-ethereum",
  "app-cardano",
  "app-u2f",
  "firmware",
  "c-unit-testing",
]

platform-bitbox02 = []
platform-bitbox02plus = ["util/sha2", "bitbox02-noise", "bitbox02-rust"]

bootloader = []
firmware = [
  "bitbox02-rust",
  "bitbox02-rust/firmware",
  "bitbox02",
  "bitbox02-noise",
  "util/sha2",
  "util/firmware",
  "der",
  "bitbox-aes",
]

# Only to be enabled in Rust unit tests.
testing = ["bitbox02-rust/testing", "bitbox02/testing"]

# Active when the Rust code is compiled to be linked into the C unit tests and simulator.
c-unit-testing = ["bitbox02-rust/c-unit-testing", "bitbox02/c-unit-testing", "util/c-unit-testing"]

simulator-graphical = [
  "app-bitcoin",
  "app-litecoin",
  "app-ethereum",
  "app-cardano",
  "firmware",
]

app-ethereum = [
  # enable this feature in the deps
  "bitbox02-rust/app-ethereum",
  "bitbox02/app-ethereum",
]

app-bitcoin = [
  # enable this feature in the deps
  "bitbox02-rust/app-bitcoin",
]

app-litecoin = [
  # enable this feature in the deps
  "bitbox02-rust/app-litecoin",
]

app-u2f = [
  # enable this feature in the deps
  "bitbox02-rust/app-u2f",
  "util/p256",
]

app-cardano = [
 # enable this feature in the deps
  "bitbox02-rust/app-cardano",
]

factory-setup = []

rtt = ["util/rtt"]
