# SPDX-License-Identifier: Apache-2.0

[package]
name = "bitbox02"
version = "0.1.0"
authors = ["Shift Crypto AG <support@bitbox.swiss>"]
edition = "2024"
description = "Idiomatic rust bindings for C code in bitbox02-firmware"
license = "Apache-2.0"

[dependencies]
bitbox02-sys = {path="../bitbox02-sys"}
util = {path = "../util"}
zeroize = { workspace = true }
bitcoin = { workspace = true }
bip39 = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
bitbox-aes = { path = "../bitbox-aes" }
bitbox02-rust = { path = "../bitbox02-rust" }
hex_lit = { workspace = true }

[features]
# Only to be enabled in unit tests and simulators
testing = ["util/testing"]
# Enables UI stubs for rust unit tests
unit-testing = []
# Active when the Rust code is compiled to be linked into the C unit tests and simulator.
c-unit-testing = []
# Active when building for the graphical simulator
simulator-graphical = []

app-ethereum = []
app-bitcoin = []
app-litecoin = []
app-u2f = []
