# Copyright 2020 Shift Cryptosecurity AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "bitbox02"
version = "0.1.0"
authors = ["Shift Crypto AG <support@shiftcrypto.ch>"]
edition = "2018"
description = "Idiomatic rust bindings for C code in bitbox02-firmware"
license = "Apache-2.0"

[dependencies]
bitbox02-sys = {path="../bitbox02-sys"}
util = {path = "../util"}
zeroize = "1.1.0"
lazy_static = { version = "1.4.0", optional = true }

[features]
# Only to be enabled in unit tests.
testing = ["lazy_static", "bitbox02-sys/testing"]

app-ethereum = []
app-bitcoin = []
app-litecoin = []
app-u2f = []
