# SPDX-License-Identifier: Apache-2.0

[package]
name = "prost-build-proto"
version = "0.1.0"
authors = ["Shift Crypto AG <support@bitbox.swiss>"]
edition = "2021"
license = "Apache-2.0"

[dependencies.prost-build]
# keep version in sync with src/rust/bitbox02-rust/Cargo.toml
version = "0.13.1"
