[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/probe-rs/rtt-target.git?rev=117d9519a5d3b1f4bc024bc05f9e3c5dec0a57f5"]
git = "https://github.com/probe-rs/rtt-target.git"
rev = "117d9519a5d3b1f4bc024bc05f9e3c5dec0a57f5"
replace-with = "vendored-sources"

[source."git+https://github.com/BitBoxSwiss/rust-bip32-ed25519?tag=v0.2.1"]
git = "https://github.com/BitBoxSwiss/rust-bip32-ed25519"
tag = "v0.2.1"
replace-with = "vendored-sources"

[source."git+https://github.com/BitBoxSwiss/rust-bip39.git?branch=bitbox-20250922"]
git = "https://github.com/BitBoxSwiss/rust-bip39.git"
branch = "bitbox-20250922"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../../external/vendor"

[build]
# Use our own copy of libsecp256k1-zpk instead of the one bundled with secp256k1-sys, also in `cargo
# test` and other cargo-based builds. This is replicated in src/CMakeLists.txt,
# test/simulator-graphical*/CMakeLists.txt for CMake-based builds.
# See https://github.com/rust-bitcoin/rust-secp256k1/tree/7c8270a8506e31731e540fab7ee1abde1f48314e/secp256k1-sys#linking-to-external-symbols
rustflags = ["--cfg", "rust_secp_no_symbol_renaming"]
