[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/digitalbitbox/rust-bip32-ed25519?tag=v0.1.2"]
git = "https://github.com/digitalbitbox/rust-bip32-ed25519"
tag = "v0.2.0"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
