# SPDX-License-Identifier: Apache-2.0

[package]
name = "util"
version = "0.1.0"
authors = ["Shift Crypto AG <support@bitbox.swiss>"]
edition = "2024"
license = "Apache-2.0"

[dependencies]
num-bigint = { workspace = true, default-features = false }
rtt-target = { version = "0.6.1", optional = true }
cortex-m = { workspace = true }
hex = {workspace = true}
sha2 = { workspace = true, optional = true }
p256 = { version = "0.13.2", default-features = false, features = ["arithmetic", "ecdsa"], optional = true }
bitcoin = {workspace = true}
critical-section = { version = "1.2.0", default-features = false, features = [] }

[dev-dependencies]
hex_lit = { workspace = true }

[features]
rtt = ["dep:rtt-target"]
testing = ["critical-section/std"]
c-unit-testing = ["critical-section/std"]
firmware = []
