[package]
name = "bitbox03"
version = "0.1.0"
edition = "2024"

[dependencies]
bitbox-lvgl = { path = "../bitbox-lvgl" }
tracing = { version = "0.1.41", features = ["log"], default-features = false }
