# SPDX-License-Identifier: Apache-2.0

[package]
name = "streaming-silent-payments"
version = "0.1.0"
authors = ["Shift Crypto AG <support@bitbox.swiss>"]
edition = "2024"
license = "Apache-2.0"

[dependencies]
bitcoin = { workspace = true }
bitbox-secp256k1 = { path = "../bitbox-secp256k1" }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
hex = { workspace = true }
serde_json = "1.0"
