# SPDX-License-Identifier: Apache-2.0

[package]
name = "bitbox02-sys"
version = "0.1.0"
authors = ["Shift Crypto AG <support@bitbox.swiss>"]
edition = "2024"
description = "Rust bindings for C code in bitbox02-firmware"
license = "Apache-2.0"

[dependencies]
util = {path = "../util"}

[build-dependencies]
cc = {version="1.2", features=["parallel"]}
