[package]
name = "bitbox03-firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
bitbox-lvgl = { path = "../bitbox-lvgl" }
st-drivers-sys = { path = "../st-drivers-sys" }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["critical-section-single-core"]}
arrayvec = {version = "0.7", default-features = false}
embedded-alloc = { version = "0.7" }
stm32u5 = { version = "0.16", features = ["stm32u5a9"]}
