[package]
name = "bitbox03-firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
bitbox-lvgl = { path = "../bitbox-lvgl" }
st-drivers-sys = { path = "../st-drivers-sys" }
cortex-m-rt = "0.7"
cortex-m = "0.7"
